const router = require('express').Router()
const multer = require('multer')
const projects = require('../controllers/projects/projects.controller')
const projectTasks = require('../controllers/projects/projectTasks.controller')
const projectSettings = require('../controllers/projects/projectSettings.controller')
const globalSettings = require('../controllers/projects/globalSettings.controller')
const projectAccess = require('../controllers/projects/projectAccess.controller')
const briefs = require('../controllers/briefs.controller')
const meetings = require('../controllers/projectMeetings.controller')
const projectReports = require('../controllers/projectReports.controller')
const clientPortal = require('../controllers/clientPortal.controller')
const { auth } = require('../middleware/auth')
const { resolveWorkspace, workspaceAdminOnly } = require('../middleware/workspace')

const uploadPortalBanner = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } })

router.use(auth)
router.use(resolveWorkspace)

router.get('/',                            projects.list)
router.get('/all',                         workspaceAdminOnly, projects.listAll)
router.get('/settings',                    workspaceAdminOnly, globalSettings.getGlobalSettings)
router.patch('/settings',                  workspaceAdminOnly, globalSettings.saveGlobalSettings)
router.post('/settings/late-notification/test', workspaceAdminOnly, globalSettings.testLateNotification)
router.post('/settings/marketing-digest/test', workspaceAdminOnly, globalSettings.testMarketingDigest)
router.get('/settings/ai-usage',           workspaceAdminOnly, globalSettings.getAiUsage)
router.get('/:id/members',                 projects.getMembers)
router.get('/:id/tasks',                   projectTasks.projectTasks)
router.get('/:id/completed',               projectTasks.projectCompletedHistory)
router.post('/',                           workspaceAdminOnly, projects.create)
router.put('/:id',                         workspaceAdminOnly, projects.update)
router.patch('/:id/star',                  projects.toggleStar)
router.put('/:id/links',                   projectSettings.saveLinks)
router.get('/:id/accesos',                 projectAccess.listAccesses)
router.post('/:id/accesos',                projectAccess.addAccess)
router.get('/:id/accesos/:accessId/reveal', projectAccess.revealAccess)
router.delete('/:id/accesos/:accessId',    projectAccess.deleteAccess)
router.patch('/:id/situation',             projectSettings.saveSituation)
router.patch('/:id/info',                  projectSettings.saveInfo)
router.get('/:id/briefs',                  briefs.listBriefs)
router.put('/:id/briefs/:type',            briefs.saveBrief)
router.delete('/:id/briefs/:type',         briefs.deleteBrief)
router.get('/:id/reports/hours-history',   projectReports.hoursHistory)

// Portal de cliente (acceso externo, solo lectura, ver clientPortal.controller.js)
router.get('/:id/client-portal',           clientPortal.getClientPortal)
router.put('/:id/client-portal',           clientPortal.saveClientPortal)
router.delete('/:id/client-portal',        clientPortal.deleteClientPortal)
router.post('/:id/client-portal/banner',   uploadPortalBanner.single('image'), clientPortal.uploadPortalBanner)
router.delete('/:id/client-portal/banner', clientPortal.deletePortalBanner)

// Contactos autorizados del portal (multi-contacto) — ABM independiente del PUT de arriba
router.get('/:id/client-portal/contacts',           clientPortal.listContacts)
router.post('/:id/client-portal/contacts',          clientPortal.createContact)
router.patch('/:id/client-portal/contacts/:cid',    clientPortal.updateContact)
router.delete('/:id/client-portal/contacts/:cid',   clientPortal.deleteContact)

// Reuniones del proyecto (formato L10 sin puntaje; con cronómetro y to-dos al dashboard)
router.get('/:id/meetings',                                 meetings.listMeetings)
router.post('/:id/meetings',                                meetings.createMeeting)
router.patch('/:id/meetings/:mid',                          meetings.updateMeeting)
router.delete('/:id/meetings/:mid',                         meetings.deleteMeeting)
router.post('/:id/meetings/:mid/start',                     meetings.startMeeting)
router.post('/:id/meetings/:mid/finish',                    meetings.finishMeeting)
router.post('/:id/meetings/:mid/participants',              meetings.addParticipant)
router.delete('/:id/meetings/:mid/participants/:uid',       meetings.removeParticipant)
router.post('/:id/meetings/:mid/todos',                     meetings.createTodo)
router.patch('/:id/meetings/:mid/todos/:tid',               meetings.updateTodo)
router.delete('/:id/meetings/:mid/todos/:tid',              meetings.deleteTodo)
router.post('/:id/meetings/:mid/todos/:tid/send-to-dashboard', meetings.sendTodoToDashboard)

module.exports = router
