const router = require('express').Router()
const c = require('../controllers/projects.controller')
const briefs = require('../controllers/briefs.controller')
const meetings = require('../controllers/projectMeetings.controller')
const clientPortal = require('../controllers/clientPortal.controller')
const { auth } = require('../middleware/auth')
const { resolveWorkspace, workspaceAdminOnly } = require('../middleware/workspace')

router.use(auth)
router.use(resolveWorkspace)

router.get('/',                            c.list)
router.get('/all',                         workspaceAdminOnly, c.listAll)
router.get('/settings',                    workspaceAdminOnly, c.getGlobalSettings)
router.patch('/settings',                  workspaceAdminOnly, c.saveGlobalSettings)
router.post('/settings/late-notification/test', workspaceAdminOnly, c.testLateNotification)
router.get('/settings/ai-usage',           workspaceAdminOnly, c.getAiUsage)
router.get('/:id/members',                 c.getMembers)
router.get('/:id/tasks',                   c.projectTasks)
router.get('/:id/completed',               c.projectCompletedHistory)
router.post('/',                           workspaceAdminOnly, c.create)
router.put('/:id',                         workspaceAdminOnly, c.update)
router.patch('/:id/star',                  c.toggleStar)
router.put('/:id/links',                   c.saveLinks)
router.get('/:id/accesos',                 c.listAccesses)
router.post('/:id/accesos',                c.addAccess)
router.get('/:id/accesos/:accessId/reveal', c.revealAccess)
router.delete('/:id/accesos/:accessId',    c.deleteAccess)
router.patch('/:id/situation',             c.saveSituation)
router.patch('/:id/info',                  c.saveInfo)
router.get('/:id/briefs',                  briefs.listBriefs)
router.put('/:id/briefs/:type',            briefs.saveBrief)
router.delete('/:id/briefs/:type',         briefs.deleteBrief)

// Portal de cliente (acceso externo, solo lectura, ver clientPortal.controller.js)
router.get('/:id/client-portal',           clientPortal.getClientPortal)
router.put('/:id/client-portal',           clientPortal.saveClientPortal)
router.delete('/:id/client-portal',        clientPortal.deleteClientPortal)

// Contactos autorizados del portal (multi-contacto) — ABM independiente del PUT de arriba
router.get('/:id/client-portal/contacts',           clientPortal.listContacts)
router.post('/:id/client-portal/contacts',          clientPortal.createContact)
router.patch('/:id/client-portal/contacts/:cid',    clientPortal.updateContact)
router.delete('/:id/client-portal/contacts/:cid',   clientPortal.deleteContact)

// Reuniones del proyecto (formato L10 sin puntaje; con cronómetro y to-dos al dashboard)
router.get('/:id/meetings',                                 meetings.listMeetings)
router.post('/:id/meetings',                                meetings.createMeeting)
router.patch('/:id/meetings/:mid',                          meetings.updateMeeting)
router.delete('/:id/meetings/:mid',                         meetings.deleteMeeting)
router.post('/:id/meetings/:mid/start',                     meetings.startMeeting)
router.post('/:id/meetings/:mid/finish',                    meetings.finishMeeting)
router.post('/:id/meetings/:mid/participants',              meetings.addParticipant)
router.delete('/:id/meetings/:mid/participants/:uid',       meetings.removeParticipant)
router.post('/:id/meetings/:mid/todos',                     meetings.createTodo)
router.patch('/:id/meetings/:mid/todos/:tid',               meetings.updateTodo)
router.delete('/:id/meetings/:mid/todos/:tid',              meetings.deleteTodo)
router.post('/:id/meetings/:mid/todos/:tid/send-to-dashboard', meetings.sendTodoToDashboard)

module.exports = router
