const router = require('express').Router()
const lifecycle = require('../controllers/tasks/lifecycle.controller')
const organization = require('../controllers/tasks/organization.controller')
const history = require('../controllers/tasks/history.controller')
const delegation = require('../controllers/tasks/delegation.controller')
const following = require('../controllers/tasks/following.controller')
const { listComments, addComment, toggleReaction } = require('../controllers/comments.controller')
const { auth } = require('../middleware/auth')
const { resolveWorkspace } = require('../middleware/workspace')

router.use(auth)
router.use(resolveWorkspace)

router.get('/completed',             history.completedHistory)
router.get('/delegated',             delegation.delegated)
router.delete('/delegated',          delegation.dismissDelegated)
router.delete('/followed',           following.unfollowAll)
router.get('/followed',              following.followed)
router.post('/',                     lifecycle.create)
router.get('/:id/follow',            following.followState)
router.post('/:id/follow',           following.followTask)
router.delete('/:id/follow',         following.unfollowTask)
router.delete('/:id/delegated',      delegation.dismissDelegatedOne)
router.patch('/:id/start',           lifecycle.startTask)
router.patch('/:id/pause',           lifecycle.pauseTask)
router.patch('/:id/resume',          lifecycle.resumeTask)
router.patch('/:id/complete',        lifecycle.completeTask)
router.patch('/:id/block',           lifecycle.blockTask)
router.patch('/:id/unblock',         lifecycle.unblockTask)
router.patch('/:id/star',            organization.starTask)
router.patch('/:id/add-to-today',    organization.addToToday)
router.patch('/:id/bring-to-today',  organization.bringToToday)
router.patch('/:id/move-to-backlog', organization.moveToBacklog)
router.patch('/:id',                 lifecycle.editTask)
router.delete('/:id',                lifecycle.remove)
router.patch('/:id/duration',        lifecycle.setDuration)
router.get('/:id/comments',          listComments)
router.post('/:id/comments',         addComment)
router.post('/:id/comments/:commentId/reactions', toggleReaction)

module.exports = router
