const router = require('express').Router()
const { create, startTask, pauseTask, resumeTask, completeTask, blockTask, unblockTask, remove, editTask, setDuration, starTask, addToToday, moveToBacklog, completedHistory, delegated } = require('../controllers/tasks.controller')
const { listComments, addComment } = require('../controllers/comments.controller')
const { auth, adminOnly } = require('../middleware/auth')

router.use(auth)
router.get('/completed',  completedHistory)
router.get('/delegated',  delegated)
router.post('/', create)
router.patch('/:id/start',    startTask)
router.patch('/:id/pause',    pauseTask)
router.patch('/:id/resume',   resumeTask)
router.patch('/:id/complete', completeTask)
router.patch('/:id/block',   blockTask)
router.patch('/:id/unblock', unblockTask)
router.patch('/:id/star',          starTask)
router.patch('/:id/add-to-today',  addToToday)
router.patch('/:id/move-to-backlog', moveToBacklog)
router.patch('/:id', editTask)
router.delete('/:id', remove)
router.patch('/:id/duration', setDuration)
router.get('/:id/comments',  listComments)
router.post('/:id/comments', addComment)

module.exports = router
