const router = require('express').Router()
const { create, startTask, pauseTask, resumeTask, completeTask, blockTask, unblockTask, remove, setDuration, starTask, addToToday, moveToBacklog, completedHistory } = require('../controllers/tasks.controller')
const { auth, adminOnly } = require('../middleware/auth')

router.use(auth)
router.get('/completed', completedHistory)
router.post('/', create)
router.patch('/:id/start',    startTask)
router.patch('/:id/pause',    pauseTask)
router.patch('/:id/resume',   resumeTask)
router.patch('/:id/complete', completeTask)
router.patch('/:id/block',   blockTask)
router.patch('/:id/unblock', unblockTask)
router.patch('/:id/star',          starTask)
router.patch('/:id/add-to-today',  addToToday)
router.patch('/:id/move-to-backlog', moveToBacklog)
router.delete('/:id', remove)
router.patch('/:id/duration', adminOnly, setDuration)

module.exports = router
