/**
 * Catálogo de configuración global de la plataforma BlissTracker.
 *
 * Agregar un nuevo setting acá es suficiente: al arrancar el servidor se hace
 * upsert automático en la DB con el `default` definido. El SuperAdmin lo edita
 * desde el panel `/superadmin` → "Configuración".
 *
 * Campos:
 *   key      — identificador único, usado en getSetting('key')
 *   type     — 'integer' | 'float' | 'boolean' | 'string' | 'pricingTiers'
 *   default  — valor inicial (al crear el row por primera vez)
 *   min/max  — bounds opcionales (defensa en profundidad)
 *   group    — 'commercial' | 'operational' | 'scraping' | 'platform' (agrupa la UI)
 *   label    — nombre legible
 *   help     — descripción larga para el panel
 */
const PLATFORM_SETTINGS = [
  // ─── Comercial ─────────────────────────────────────────────────────────────
  {
    key:     'trialDays',
    type:    'integer',
    default: 14,
    min:     0,
    max:     365,
    group:   'commercial',
    label:   'Duración del trial (días)',
    help:    'Cantidad de días que duran los trials de los nuevos workspaces. Los workspaces existentes mantienen su trialEndsAt actual.',
  },
  {
    key:     'freeSeatLimit',
    type:    'integer',
    default: 3,
    min:     0,
    max:     1000,
    group:   'commercial',
    label:   'Usuarios gratis (plan Gratis)',
    help:    'Cantidad máxima de usuarios activos que un workspace puede tener sin pagar. Al vencer el trial, los workspaces con esta cantidad o menos pasan al plan Gratis (acceso completo al core, sin suscripción); los que superan el límite quedan en past_due hasta activar Pro. 0 = no hay plan gratis (todos deben pagar al vencer el trial).',
  },
  {
    key:     'defaultMonthlyTokenLimit',
    type:    'integer',
    default: 1_000_000,
    min:     0,
    group:   'commercial',
    label:   'Límite mensual de tokens de IA (default para nuevos workspaces)',
    help:    'Aplica solo a workspaces nuevos. Los existentes mantienen su monthlyTokenLimit propio (editable por workspace). 0 = ilimitado.',
  },
  {
    key:     'pricingTiers',
    type:    'pricingTiers',
    default: [
      { upTo: 19,   pricePerSeat: 3 },
      { upTo: null, pricePerSeat: 2 },
    ],
    group: 'commercial',
    label: 'Pricing tiers (USD por seat / mes)',
    help:  'Debe coincidir con el catálogo de productos en Stripe — si lo cambiás acá, actualizá también el precio en Stripe Dashboard. upTo: null = tier superior sin tope.',
  },
  {
    key:     'haikuInputCostPer1M',
    type:    'float',
    default: 0.80,
    min:     0,
    group:   'commercial',
    label:   'Costo Claude Haiku — input (USD / 1M tokens)',
    help:    'Precio actual de Anthropic para tokens de entrada de Claude Haiku. Actualizá cuando Anthropic cambie sus tarifas.',
  },
  {
    key:     'haikuOutputCostPer1M',
    type:    'float',
    default: 4.00,
    min:     0,
    group:   'commercial',
    label:   'Costo Claude Haiku — output (USD / 1M tokens)',
    help:    'Precio actual de Anthropic para tokens de salida de Claude Haiku.',
  },

  // ─── Operativo ─────────────────────────────────────────────────────────────
  {
    key:     'aiCooldownMinutes',
    type:    'integer',
    default: 60,
    min:     0,
    max:     1440,
    group:   'operational',
    label:   'Cooldown de regeneración IA (minutos)',
    help:    'Tiempo mínimo entre regeneraciones de insights diarios y análisis SEO. Aplica a insights del Dashboard y al análisis SEO de Search Console.',
  },
  {
    key:     'tokenWarningPct',
    type:    'integer',
    default: 90,
    min:     50,
    max:     99,
    group:   'operational',
    label:   'Umbral de warning de tokens (%)',
    help:    'Porcentaje de consumo a partir del cual un workspace entra en estado "warning". Debe ser menor que el umbral crítico.',
  },
  {
    key:     'tokenCriticalPct',
    type:    'integer',
    default: 95,
    min:     51,
    max:     100,
    group:   'operational',
    label:   'Umbral crítico de tokens (%)',
    help:    'Porcentaje de consumo a partir del cual un workspace entra en estado "critical". Debe ser mayor que el umbral de warning.',
  },
  {
    key:     'trialingSoonDays',
    type:    'integer',
    default: 7,
    min:     1,
    max:     90,
    group:   'operational',
    label:   'Alerta "trial por vencer" (días)',
    help:    'Días restantes a partir de los cuales un trial aparece en el dashboard SuperAdmin como "próximo a vencer".',
  },
  {
    key:     'notificationReadRetentionDays',
    type:    'integer',
    default: 30,
    min:     7,
    max:     3650,
    group:   'operational',
    label:   'Retención de notificaciones leídas (días)',
    help:    'Después de cuántos días se borran las notificaciones leídas. Aplica en el cron de limpieza semanal (domingos 03:00).',
  },
  {
    key:     'notificationUnreadRetentionDays',
    type:    'integer',
    default: 90,
    min:     7,
    max:     3650,
    group:   'operational',
    label:   'Retención de notificaciones no leídas (días)',
    help:    'Después de cuántos días se borran las notificaciones no leídas (asumiendo que ya no son relevantes).',
  },
  {
    key:     'aiTokenLogsRetentionDays',
    type:    'integer',
    default: 90,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de logs de tokens IA (días)',
    help:    'Después de cuántos días se borran los registros individuales de uso de tokens. Los agregados mensuales del dashboard siguen funcionando.',
  },
  {
    key:     'loginHistoryRetentionDays',
    type:    'integer',
    default: 180,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de historial de logins (días)',
    help:    'Después de cuántos días se borran los registros de UserLogin. Afecta el panel RRHH → Ingresos.',
  },
  {
    key:     'dailyInsightRetentionDays',
    type:    'integer',
    default: 365,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de insights diarios (días)',
    help:    'Después de cuántos días se borran los DailyInsight cacheados. No afecta los UserInsightMemory (perfil semanal de aprendizaje).',
  },
  {
    key:     'emailLogRetentionDays',
    type:    'integer',
    default: 180,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de logs de emails (días)',
    help:    'Después de cuántos días se borran los EmailLog. Afecta el panel SuperAdmin → Emails.',
  },
  {
    key:     'socialImageOrphanRetentionDays',
    type:    'integer',
    default: 7,
    min:     1,
    max:     365,
    group:   'operational',
    label:   'Retención de imágenes sociales huérfanas (días)',
    help:    'Las imágenes de RRSS (SocialImage) que ya no referencia ningún snapshot ni informe ("huérfanas", típicamente generadas al refrescar) se borran en la limpieza semanal si tienen más de estos días. NO afecta las imágenes en uso. La limpieza inmediata con VACUUM está en SuperAdmin → Almacenamiento.',
  },
  {
    key:     'serpSnapshotRetentionDays',
    type:    'integer',
    default: 180,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de snapshots SERP (días)',
    help:    'Después de cuántos días se borran los SerpSnapshot (captura completa de SerpAPI por keyword). Es una de las tablas que más crece por keyword; la app sólo usa el snapshot más reciente (<24h), así que los viejos son sólo histórico. No afecta el tracking de posiciones (KeywordRanking).',
  },
  {
    key:     'followerLogRetentionDays',
    type:    'integer',
    default: 180,
    min:     60,
    max:     3650,
    group:   'operational',
    label:   'Retención de logs diarios de seguidores (días)',
    help:    'Después de cuántos días se borran los logs DIARIOS de seguidores de RRSS (Instagram/TikTok/LinkedIn/Facebook/YouTube + competidores). Se necesitan al menos los del mes en curso para calcular "nuevos en el mes"; por eso el piso es 60 días. NO afecta los snapshots mensuales de los informes.',
  },
  {
    key:     'conversionEventRetentionDays',
    type:    'integer',
    default: 365,
    min:     30,
    max:     3650,
    group:   'operational',
    label:   'Retención de eventos de conversión (días)',
    help:    'Después de cuántos días se borran los ConversionEvent (instrumentación del funnel signup→trial→paid). El funnel del panel SuperAdmin usa por defecto los últimos 30 días.',
  },
  {
    key:     'accessLogRetentionDays',
    type:    'integer',
    default: 365,
    min:     90,
    max:     3650,
    group:   'operational',
    label:   'Retención de logs de accesos a credenciales (días)',
    help:    'Después de cuántos días se borran los ProjectAccessLog (auditoría de quién reveló una contraseña/2FA de un proyecto). Piso alto (90 días) por ser un registro de auditoría de seguridad.',
  },

  // ─── Scraping (Apify) ──────────────────────────────────────────────────────
  // Actores y topes de posts por red. El token de Apify (APIFY_API_TOKEN) sigue
  // siendo una env — es la credencial real y no se edita desde el panel.
  {
    key:     'apifyInstagramActor',
    type:    'string',
    default: '',
    group:   'scraping',
    label:   'Actor de Apify para Instagram (scraping)',
    help:    'ID del actor de Apify que scrapea perfiles de Instagram. Se acepta "usuario/actor" o "usuario~actor" — se normaliza solo. Vacío = usa la env APIFY_INSTAGRAM_ACTOR; si ambos están vacíos cae al default oficial `apify~instagram-profile-scraper`. Editable acá para probar/cambiar de actor sin redeploy. Si el actor usa otras claves de input/output, el mapeo se ajusta en runApifyInstagram/normalizeApifyProfile (socialScrape.service.js).',
  },
  {
    key:     'apifyInstagramPostsLimit',
    type:    'integer',
    default: 0,
    min:     0,
    max:     200,
    group:   'scraping',
    label:   'Posts a traer por scrape de Instagram',
    help:    'Cantidad de publicaciones recientes que trae cada scrape de Instagram (debe cubrir el mes completo). 0 = usa la variable de entorno APIFY_INSTAGRAM_POSTS_LIMIT o el default (60). Subir si una cuenta postea mucho y los meses quedan incompletos.',
  },
  {
    key:     'apifyInstagramPostsActor',
    type:    'string',
    default: '',
    group:   'scraping',
    label:   'Actor de Apify para posts de Instagram (2ª llamada)',
    help:    'El actor de perfil (apify~instagram-profile-scraper) trae un `latestPosts` capado (~12) y NO ordenado por fecha, así que en cuentas activas se pierden publicaciones del mes. Con este actor de posts se hace una 2ª llamada que trae la lista completa y ordenada, y se fusiona con la del perfil (los seguidores/datos del perfil siguen saliendo de la 1ª llamada). Costo Apify ~2x por scrape de Instagram (incluye competidores). Se acepta "usuario/actor" o "usuario~actor". Vacío = usa la env APIFY_INSTAGRAM_POSTS_ACTOR; si ambos vacíos → NO se hace la 2ª llamada (comportamiento anterior). Recomendado: `apify~instagram-post-scraper`. Para desactivar explícitamente: poné "none".',
  },
  {
    key:     'igCollabScrapeEnabled',
    type:    'boolean',
    default: false,
    group:   'scraping',
    label:   'Sumar collabs en Instagram por token (scrape del grid)',
    help:    'En las cuentas de Instagram conectadas por API oficial/token, la Graph API NO devuelve las publicaciones en colaboración al co-autor (aparecen solo en el perfil del autor original). Con esto activado, cada lectura de métricas hace un scrape simple del grid público (requiere APIFY_API_TOKEN + cuenta pública) y fusiona los collabs que falten al conteo/promedios del mes. Se cachea 6h en memoria por integración para no scrapear en cada visita. Costo Apify: 1 scrape de perfil por integración cada 6h. Off = comportamiento anterior (solo lo que devuelve la API oficial).',
  },
  {
    key:     'apifyLinkedinActor',
    type:    'string',
    default: '',
    group:   'scraping',
    label:   'Actor de Apify para LinkedIn (scraping)',
    help:    'ID del actor de Apify que scrapea Company Pages de LinkedIn. Se acepta tanto "usuario/actor" (como lo muestra Apify) como "usuario~actor" — se normaliza solo. Importante: tiene que ser un actor que devuelva métricas de la página (seguidores y/o posts), no un utilitario (ej. un "id-to-slug finder" NO sirve). Editable acá para probar e ir cambiando de actor sin redeploy. Vacío = usa la env APIFY_LINKEDIN_ACTOR; si ambos están vacíos → SCRAPE_NOT_CONFIGURED. Si el actor usa otras claves de input/output, el mapeo se ajusta en runApifyLinkedin/normalizeApifyCompany (socialScrape.service.js).',
  },
  {
    key:     'apifyLinkedinPostsLimit',
    type:    'integer',
    default: 0,
    min:     0,
    max:     200,
    group:   'scraping',
    label:   'Posts a traer por scrape de LinkedIn',
    help:    'Cantidad de posts recientes que trae cada scrape de LinkedIn (debe cubrir el mes completo). 0 = usa la variable de entorno APIFY_LINKEDIN_POSTS_LIMIT o el default (30). Subir si una página postea mucho y los meses quedan incompletos.',
  },
  {
    key:     'apifyFacebookActor',
    type:    'string',
    default: '',
    group:   'scraping',
    label:   'Actor de Apify para Facebook (scraping)',
    help:    'ID del actor de Apify que scrapea Páginas de Facebook. Se acepta "usuario/actor" o "usuario~actor" — se normaliza solo. Tiene que devolver métricas de la página (seguidores y/o posts). Editable acá para probar e ir cambiando de actor sin redeploy. Vacío = usa la env APIFY_FACEBOOK_ACTOR; si ambos están vacíos → SCRAPE_NOT_CONFIGURED. Si el actor usa otras claves de input/output, el mapeo se ajusta en runApifyFacebook/normalizeApifyFacebook (socialScrape.service.js).',
  },
  {
    key:     'apifyFacebookPostsLimit',
    type:    'integer',
    default: 0,
    min:     0,
    max:     200,
    group:   'scraping',
    label:   'Posts a traer por scrape de Facebook',
    help:    'Cantidad de posts recientes que trae cada scrape de Facebook (debe cubrir el mes completo). 0 = usa la variable de entorno APIFY_FACEBOOK_POSTS_LIMIT o el default (30). Subir si una página postea mucho y los meses quedan incompletos.',
  },

  // ─── Notificaciones de plataforma ──────────────────────────────────────────
  // Casilla interna del equipo BlissTracker que recibe avisos operativos
  // (feedback, nuevos workspaces, pagos, churn). Si platformAdminEmail está
  // vacío, NINGÚN aviso se envía (sistema apagado).
  {
    key:     'platformAdminEmail',
    type:    'string',
    default: '',
    group:   'platform',
    label:   'Casilla de administración (recibe avisos)',
    help:    'Email del equipo BlissTracker que recibe los avisos internos de la plataforma (feedback, nuevos workspaces, pagos, cancelaciones). Vacío = no se envía ningún aviso. Para varias casillas, separá con coma.',
  },
  {
    key:     'platformEmailFrom',
    type:    'string',
    default: '',
    group:   'platform',
    label:   'Remitente global de emails (From)',
    help:    'Desde qué dirección salen todos los emails de la plataforma. Formato: "BlissTracker <noreply@blisstracker.app>". El dominio debe estar verificado en Resend. Vacío = usa la variable de entorno EMAIL_FROM. Un proyecto con emailFrom propio sigue teniendo prioridad para los emails de ese workspace.',
  },
  {
    key:     'notifyOnFeedback',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: feedback (sugerencias / bugs)',
    help:    'Enviar un aviso a la casilla de administración cada vez que un usuario de cualquier workspace envía una sugerencia o reporta un error.',
  },
  {
    key:     'notifyOnNewWorkspace',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: nuevo workspace registrado',
    help:    'Enviar un aviso cuando se registra un nuevo workspace (alta de cliente / inicio de trial).',
  },
  {
    key:     'notifyOnPaymentSuccess',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: pago exitoso',
    help:    'Enviar un aviso cuando un workspace activa o renueva su suscripción Pro (pago confirmado por Stripe).',
  },
  {
    key:     'notifyOnPaymentFailed',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: pago fallido',
    help:    'Enviar un aviso cuando Stripe no puede cobrar una suscripción (morosidad / tarjeta rechazada).',
  },
  {
    key:     'notifyOnCancellation',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: cancelación de suscripción',
    help:    'Enviar un aviso cuando un workspace cancela su plan Pro (churn).',
  },
  {
    key:     'notifyOnDeletionRequest',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: solicitud de borrado de workspace',
    help:    'Enviar un aviso cuando un owner programa la eliminación de su workspace (48h de gracia antes del borrado definitivo).',
  },
  {
    key:     'notifyOnTrialExpired',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: trial vencido a past_due',
    help:    'Enviar un aviso cuando un trial vence sin conversión y el workspace pasa a past_due (supera el límite de usuarios gratis).',
  },
  {
    key:     'notifyOnScrapeError',
    type:    'boolean',
    default: true,
    group:   'platform',
    label:   'Avisar: error de scraping de RRSS (Apify)',
    help:    'Enviar un aviso cuando el scraping de redes sociales (Apify) falla — por ejemplo si la cuenta de Apify se queda sin crédito, el token es inválido o el proveedor responde con error. Limitado a un aviso cada 6 horas por tipo de error para no saturar la casilla durante el cron mensual.',
  },
]

const SETTINGS_BY_KEY = Object.fromEntries(PLATFORM_SETTINGS.map(s => [s.key, s]))

const RETENTION_KEYS = [
  'notificationReadRetentionDays',
  'notificationUnreadRetentionDays',
  'aiTokenLogsRetentionDays',
  'loginHistoryRetentionDays',
  'dailyInsightRetentionDays',
  'emailLogRetentionDays',
  'socialImageOrphanRetentionDays',
  'serpSnapshotRetentionDays',
  'followerLogRetentionDays',
  'conversionEventRetentionDays',
  'accessLogRetentionDays',
]

module.exports = { PLATFORM_SETTINGS, SETTINGS_BY_KEY, RETENTION_KEYS }
